// Code generated by MockGen. DO NOT EDIT.
// Source: flight.go
//
// Generated by this command:
//
//	mockgen -package=mockservice -source=flight.go -destination=../.././../test/mock/service/flight.go
//

// Package mockservice is a generated GoMock package.
package mockservice

import (
	context "context"
	reflect "reflect"

	flight "github.com/alhamsya/bookcabin/internal/core/domain/flight"
	response "github.com/alhamsya/bookcabin/internal/core/domain/response"
	gomock "go.uber.org/mock/gomock"
)

// MockFlightService is a mock of FlightService interface.
type MockFlightService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightServiceMockRecorder
	isgomock struct{}
}

// MockFlightServiceMockRecorder is the mock recorder for MockFlightService.
type MockFlightServiceMockRecorder struct {
	mock *MockFlightService
}

// NewMockFlightService creates a new mock instance.
func NewMockFlightService(ctrl *gomock.Controller) *MockFlightService {
	mock := &MockFlightService{ctrl: ctrl}
	mock.recorder = &MockFlightServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightService) EXPECT() *MockFlightServiceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockFlightService) Search(ctx context.Context, param *flight.ReqSearch) (response.Common, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, param)
	ret0, _ := ret[0].(response.Common)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockFlightServiceMockRecorder) Search(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFlightService)(nil).Search), ctx, param)
}
