// Code generated by MockGen. DO NOT EDIT.
// Source: airline.go
//
// Generated by this command:
//
//	mockgen -package=mockrepo -source=airline.go -destination=../.././../mock/repository/airline.go
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	modelFlight "github.com/alhamsya/bookcabin/internal/core/domain/flight"
	gomock "go.uber.org/mock/gomock"
)

// MockAirAsiaRepo is a mock of AirAsiaRepo interface.
type MockAirAsiaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAirAsiaRepoMockRecorder
	isgomock struct{}
}

// MockAirAsiaRepoMockRecorder is the mock recorder for MockAirAsiaRepo.
type MockAirAsiaRepoMockRecorder struct {
	mock *MockAirAsiaRepo
}

// NewMockAirAsiaRepo creates a new mock instance.
func NewMockAirAsiaRepo(ctrl *gomock.Controller) *MockAirAsiaRepo {
	mock := &MockAirAsiaRepo{ctrl: ctrl}
	mock.recorder = &MockAirAsiaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAirAsiaRepo) EXPECT() *MockAirAsiaRepoMockRecorder {
	return m.recorder
}

// GetFlight mocks base method.
func (m *MockAirAsiaRepo) GetFlight(ctx context.Context) ([]modelFlight.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlight", ctx)
	ret0, _ := ret[0].([]modelFlight.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlight indicates an expected call of GetFlight.
func (mr *MockAirAsiaRepoMockRecorder) GetFlight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlight", reflect.TypeOf((*MockAirAsiaRepo)(nil).GetFlight), ctx)
}

// MockBatikRepo is a mock of BatikRepo interface.
type MockBatikRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBatikRepoMockRecorder
	isgomock struct{}
}

// MockBatikRepoMockRecorder is the mock recorder for MockBatikRepo.
type MockBatikRepoMockRecorder struct {
	mock *MockBatikRepo
}

// NewMockBatikRepo creates a new mock instance.
func NewMockBatikRepo(ctrl *gomock.Controller) *MockBatikRepo {
	mock := &MockBatikRepo{ctrl: ctrl}
	mock.recorder = &MockBatikRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatikRepo) EXPECT() *MockBatikRepoMockRecorder {
	return m.recorder
}

// GetFlight mocks base method.
func (m *MockBatikRepo) GetFlight(ctx context.Context) ([]modelFlight.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlight", ctx)
	ret0, _ := ret[0].([]modelFlight.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlight indicates an expected call of GetFlight.
func (mr *MockBatikRepoMockRecorder) GetFlight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlight", reflect.TypeOf((*MockBatikRepo)(nil).GetFlight), ctx)
}

// MockGarudaRepo is a mock of GarudaRepo interface.
type MockGarudaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGarudaRepoMockRecorder
	isgomock struct{}
}

// MockGarudaRepoMockRecorder is the mock recorder for MockGarudaRepo.
type MockGarudaRepoMockRecorder struct {
	mock *MockGarudaRepo
}

// NewMockGarudaRepo creates a new mock instance.
func NewMockGarudaRepo(ctrl *gomock.Controller) *MockGarudaRepo {
	mock := &MockGarudaRepo{ctrl: ctrl}
	mock.recorder = &MockGarudaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGarudaRepo) EXPECT() *MockGarudaRepoMockRecorder {
	return m.recorder
}

// GetFlight mocks base method.
func (m *MockGarudaRepo) GetFlight(ctx context.Context) ([]modelFlight.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlight", ctx)
	ret0, _ := ret[0].([]modelFlight.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlight indicates an expected call of GetFlight.
func (mr *MockGarudaRepoMockRecorder) GetFlight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlight", reflect.TypeOf((*MockGarudaRepo)(nil).GetFlight), ctx)
}

// MockLionRepo is a mock of LionRepo interface.
type MockLionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLionRepoMockRecorder
	isgomock struct{}
}

// MockLionRepoMockRecorder is the mock recorder for MockLionRepo.
type MockLionRepoMockRecorder struct {
	mock *MockLionRepo
}

// NewMockLionRepo creates a new mock instance.
func NewMockLionRepo(ctrl *gomock.Controller) *MockLionRepo {
	mock := &MockLionRepo{ctrl: ctrl}
	mock.recorder = &MockLionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLionRepo) EXPECT() *MockLionRepoMockRecorder {
	return m.recorder
}

// GetFlight mocks base method.
func (m *MockLionRepo) GetFlight(ctx context.Context) ([]modelFlight.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlight", ctx)
	ret0, _ := ret[0].([]modelFlight.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlight indicates an expected call of GetFlight.
func (mr *MockLionRepoMockRecorder) GetFlight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlight", reflect.TypeOf((*MockLionRepo)(nil).GetFlight), ctx)
}
